---
- hosts: 127.0.0.1
  connection: local
  roles:
    - { role: utils }
    # - { role: jahrik.yay, install: true }
    - { role: docker }
    - { role: neovim }
    - { role: ssh_key }
    - { role: zsh }


  #   collections:
  #   - name: community.docker

  # - name: Install stylua
  #   become: yes
  #   aur_packages:
  #     name:
  #     - styllua
  #   state: latest

  # # Install yay with https://galaxy.ansible.com/jahrik/yay

  # - name: install yay
  #   roles:
  #     - role: jahrik.yay