---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars.yml
  roles:
    - name: utils
    # - name: { jahrik.yay, install: true } 
    - name: docker
    - name: ssh_key
    - name: neovim
    - name: zsh
    - name: dotfiles
    - name: stow
    


  #   collections:
  #   - name: community.docker

  # - name: Install stylua
  #   become: yes
  #   aur_packages:
  #     name:
  #     - styllua
  #   state: latest

  # # Install yay with https://galaxy.ansible.com/jahrik/yay

  # - name: install yay
  #   roles:
  #     - role: jahrik.yay