---
# tasks file for zsh
- name: Install zsh
  become: true
  ansible.builtin.package:
    name:
    - zsh
    state: latest
  register: zsh

- name: Active zsh
  become: true
  ansible.builtin.command: "chsh -s /usr/bin/zsh romain {{ ansible_env['USER'] }}"
  when: not ansible_facts['user_shell'] == "/usr/bin/zsh"

- name: test_ohmyzsh_folder
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: ohmyzsh_folder

- name: Download ohmyzsh
  git: 
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /tmp/oh-my-zsh
    depth: 1
  # when: not ohmyzsh_folder.stat.exists
  
- name: Install ohmyzsh
  ansible.builtin.command: sh /tmp/oh-my-zsh/tools/install.sh
  when: not ohmyzsh_folder.stat.exists

- name: zsh-auto-suggestion
  git: 
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  # a ajouter l'activation du plugin dans .zshrc