---
# tasks file for utils
- name: System
  become: true
  ansible.builtin.package:
    name:
    - htop
    - nmap
    - man-db
    - nerd-fonts
    - zsh
    - git
    - stylua
    - stow
    - tree
    state: latest

- name: App
  become: true
  ansible.builtin.package:
    name:
    - firefox
    - vscode
    - alacritty
    state: latest

- name: Languages
  become: true
  ansible.builtin.package:
    name:
    - go
    state: latest

- name: DevOps
  become: true
  ansible.builtin.package:
    name:
    - terraform
    state: latest