---
# tasks file for docker
- name: Install
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: latest
  become: true

- name: Enable service
  ansible.builtin.systemd:
    enabled: yes
    name: docker
    state: started
  become: true

- name: Add to group
  ansible.builtin.user:
    append: yes
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  become: true

- name: Set permissions for docker.sock
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: '666'
  become: true

# - name: Copy daemon.json
#   ansible.builtin.template:
#     dest: "/etc/docker/daemon.json"
#     src: "daemon.json"
#   become: yes
#   notify: restart_docker