---
# tasks file for ssh_key
- name: generate ssh key for personal github
  user:
    name: "{{ ansible_env['USER'] }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa_perso_github
    force: no