---
# tasks file for ssh_key
- name: generate ssh key for personal github
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/{{ github_key_name }}"
    force: no
  register: sshkey

- name: Check ssh key file exist
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.ssh/{{ github_key_name }}"
  register: check_sshkey

- name: Upload ssh key_file on github
  ansible.builtin.pause: 
    prompt: |
     Autoriser la clé publique sur github avant de continuer :
     
     {{ sshkey.ssh_public_key }}
     
  when: sshkey is changed