---
# tasks file for neovim
- name: Install neovim
  become: true
  ansible.builtin.package:
    name:
    - neovim
    state: latest

- name: Clone a repo
  ansible.builtin.git:
    repo: "{{ github_address }}/nvim_config.git"
    dest: "{{ ansible_user_dir }}/.config/nvim/nvim"
    key_file: "{{ ansible_user_dir }}/.ssh/{{ github_key_name }}"
    accept_hostkey: yes
